// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdKNvaJqBwVtdGuv3QpDB-uBq_QkQ6vEg',
    appId: '1:533570197873:web:03d1290d5a9a310debbed0',
    messagingSenderId: '533570197873',
    projectId: 'atelier4-y-elyourizi-iir5g7',
    authDomain: 'atelier4-y-elyourizi-iir5g7.firebaseapp.com',
    storageBucket: 'atelier4-y-elyourizi-iir5g7.appspot.com',
    measurementId: 'G-94TYFMWZ8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn73KqTSmincoQ8aCodKxF--s5N9TYj8U',
    appId: '1:533570197873:android:b5123551f2612b06ebbed0',
    messagingSenderId: '533570197873',
    projectId: 'atelier4-y-elyourizi-iir5g7',
    storageBucket: 'atelier4-y-elyourizi-iir5g7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3AC2nEfjrLk13PfLBe8OyBT_8C9wYQA4',
    appId: '1:533570197873:ios:8e1511153d6984a1ebbed0',
    messagingSenderId: '533570197873',
    projectId: 'atelier4-y-elyourizi-iir5g7',
    storageBucket: 'atelier4-y-elyourizi-iir5g7.appspot.com',
    iosBundleId: 'com.example.atelier4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3AC2nEfjrLk13PfLBe8OyBT_8C9wYQA4',
    appId: '1:533570197873:ios:8e1511153d6984a1ebbed0',
    messagingSenderId: '533570197873',
    projectId: 'atelier4-y-elyourizi-iir5g7',
    storageBucket: 'atelier4-y-elyourizi-iir5g7.appspot.com',
    iosBundleId: 'com.example.atelier4',
  );
}
